name: Publish release

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Publish release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2.0.0
        with:
          node-version: '14'
          check-latest: true
      - run: curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
      - name: release
        id: release
        run: make semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        if: steps.release.outputs.output_msg != '' && steps.release.outputs.output_msg != null
        uses: crazy-max/ghaction-docker-buildx@v3
      - name: Cache Docker layers
        if: steps.release.outputs.output_msg != '' && steps.release.outputs.output_msg != null
        uses: actions/cache@v2
        id: cache
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Login to DockerHub
        if: steps.release.outputs.output_msg != '' && steps.release.outputs.output_msg != null
        uses: crazy-max/ghaction-docker-login@v1
        with:
          registry: quay.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker Buildx (push)
        if: steps.release.outputs.output_msg != '' && steps.release.outputs.output_msg != null
        run: make docker-image-build-push
        env:
          VERSION: ${{ steps.release.outputs.output_msg }}
